"""
Render a proposed dimensional model into CREATE TABLE + MERGE INTO SQL.

Input: a Python dict matching the proposal schema (see `agent.graph.ProposalModel`).
Output: a single SQL string with `;`-separated idempotent statements that the
apply_ddl job runs against the SQL warehouse.

For dimensions with `scd: type2` we emit MERGE patterns that close out prior current
rows and insert new ones; for `type1` we do a straightforward MERGE/UPSERT.
"""
from __future__ import annotations

import os
from typing import Any

from jinja2 import Environment, StrictUndefined


def _generator_name() -> str:
    """Identifier stamped into generated SQL headers. Configurable via env var.

    Defaults to the served model name when set (env var injected by Model Serving), or a
    neutral string otherwise. No hardcoded product/agent name.
    """
    return (
        os.environ.get("AGENT_GENERATOR_NAME")
        or os.environ.get("MLFLOW_MODEL_NAME")
        or "ai-modeler-agent"
    )


_TEMPLATE = """
-- =============================================================================
-- Generated by {{ generator }}
-- Proposal: {{ proposal_id }} (version {{ version }})
-- Catalog:  {{ catalog }}
-- =============================================================================

USE CATALOG {{ catalog }};
USE SCHEMA {{ schema }};

{% for dim in dims %}
-- ---- Dimension: {{ dim.name }} ({{ dim.scd }}) ----
CREATE TABLE IF NOT EXISTS {{ catalog }}.{{ schema }}.{{ dim.name }} (
{% for c in dim.columns -%}
  {{ c.name }} {{ c.type }}{% if c.comment %} COMMENT '{{ c.comment | replace("'", "''") }}'{% endif %}{% if not loop.last %},{% endif %}
{% endfor %}
)
USING DELTA
COMMENT '{{ dim.comment | replace("'", "''") if dim.comment else "" }}';

{% set src_names = dim.source_columns | map(attribute='name') | list %}
{% if dim.scd == 'type2' %}
-- SCD2 merge for {{ dim.name }}
MERGE INTO {{ catalog }}.{{ schema }}.{{ dim.name }} AS tgt
USING (
  SELECT
    {% for c in dim.source_columns -%}
    src.{{ c.source }} AS {{ c.name }}{% if not loop.last %},{% endif %}
    {% endfor %}
  FROM {{ catalog }}.{{ silver_schema }}.{{ dim.source_table }} src
) AS s
ON tgt.{{ dim.natural_key }} = s.{{ dim.natural_key }} AND tgt.is_current = TRUE
WHEN MATCHED AND (
    {% for c in dim.scd2_change_cols -%}
    NOT (tgt.{{ c }} <=> s.{{ c }}){% if not loop.last %} OR {% endif %}
    {% endfor %}
) THEN UPDATE SET
    is_current = FALSE,
    scd_end_date = current_date()
WHEN NOT MATCHED THEN INSERT (
    {% for c in dim.columns -%}{{ c.name }}{% if not loop.last %}, {% endif %}{% endfor %}
) VALUES (
    {% for c in dim.columns -%}
    {% if c.name == 'is_current' %}TRUE
    {%- elif c.name == 'scd_start_date' %}current_date()
    {%- elif c.name == 'scd_end_date' %}NULL
    {%- elif c.name.endswith('_sk') %}xxhash64(s.{{ dim.natural_key }})
    {%- elif c.name in src_names %}s.{{ c.name }}
    {%- else %}NULL /* unsourced */
    {%- endif %}{% if not loop.last %}, {% endif %}
    {% endfor %}
);
{% else %}
-- SCD1 merge for {{ dim.name }}
MERGE INTO {{ catalog }}.{{ schema }}.{{ dim.name }} AS tgt
USING (
  SELECT
    {% for c in dim.source_columns -%}
    src.{{ c.source }} AS {{ c.name }}{% if not loop.last %},{% endif %}
    {% endfor %}
  FROM {{ catalog }}.{{ silver_schema }}.{{ dim.source_table }} src
) AS s
ON tgt.{{ dim.natural_key }} = s.{{ dim.natural_key }}
WHEN MATCHED THEN UPDATE SET
    {% for c in dim.columns if not c.name.endswith('_sk') and c.name != dim.natural_key and c.name in src_names -%}
    tgt.{{ c.name }} = s.{{ c.name }}{{ ',' if not loop.last else '' }}
    {% endfor %}
WHEN NOT MATCHED THEN INSERT (
    {% for c in dim.columns -%}{{ c.name }}{% if not loop.last %}, {% endif %}{% endfor %}
) VALUES (
    {% for c in dim.columns -%}
    {% if c.name.endswith('_sk') %}xxhash64(s.{{ dim.natural_key }})
    {%- elif c.name in src_names %}s.{{ c.name }}
    {%- else %}NULL /* unsourced */
    {%- endif %}{% if not loop.last %}, {% endif %}
    {% endfor %}
);
{% endif %}

{% endfor %}

{% for fact in facts %}
-- ---- Fact: {{ fact.name }} (grain: {{ fact.grain }}) ----
CREATE TABLE IF NOT EXISTS {{ catalog }}.{{ schema }}.{{ fact.name }} (
{% for c in fact.columns -%}
  {{ c.name }} {{ c.type }}{% if c.comment %} COMMENT '{{ c.comment | replace("'", "''") }}'{% endif %}{% if not loop.last %},{% endif %}
{% endfor %}
)
USING DELTA
COMMENT '{{ fact.comment | replace("'", "''") if fact.comment else "" }}'
{% if fact.partition_by %}PARTITIONED BY ({{ fact.partition_by | join(', ') }}){% endif %};

-- Fact MERGE for {{ fact.name }}
MERGE INTO {{ catalog }}.{{ schema }}.{{ fact.name }} AS tgt
USING (
  SELECT
    {% for c in fact.source_columns -%}
    {{ c.expr }} AS {{ c.name }}{% if not loop.last %},{% endif %}
    {% endfor %}
  FROM {{ catalog }}.{{ silver_schema }}.{{ fact.source_table }} src
  {% for j in fact.joins -%}
  LEFT JOIN {{ catalog }}.{{ schema }}.{{ j.dim }} {{ j.alias }} ON src.{{ j.src_col }} = {{ j.alias }}.{{ j.dim_col }}{{ (' AND ' ~ j.alias ~ '.is_current = TRUE') if j.scd2 else '' }}
  {% endfor %}
) AS s
ON tgt.{{ fact.natural_key }} = s.{{ fact.natural_key }}
WHEN MATCHED THEN UPDATE SET *
WHEN NOT MATCHED THEN INSERT *;

{% endfor %}
"""


def render(proposal: dict[str, Any]) -> str:
    """Render the proposal to SQL.

    `catalog` and `schema` must be present in the proposal (the designer node fills them
    in from env vars CATALOG and GOLD_SCHEMA). We do not invent defaults — that would
    silently materialize tables in the wrong place if config drifts.

    Reused dimensions (`reused_from_seed: true`) are skipped — they reference tables
    already deployed by other pipelines and need no DDL of their own. The proposal
    summary path in `backend.routers.agent` displays them; the renderer ignores them.
    """
    env = Environment(undefined=StrictUndefined, trim_blocks=True, lstrip_blocks=True)
    tpl = env.from_string(_TEMPLATE)
    catalog = proposal.get("catalog")
    schema = proposal.get("schema")
    silver_schema = proposal.get("silver_schema")
    if not catalog or not schema or not silver_schema:
        raise ValueError("Proposal is missing `catalog`, `schema`, and/or `silver_schema`.")

    renderable_dims: list[dict[str, Any]] = []
    for d in proposal.get("dims", []):
        if d.get("reused_from_seed"):
            continue
        # Shallow-copy so we don't mutate the caller's proposal dict when filling defaults.
        rd = dict(d)
        if not rd.get("scd"):
            # Documented default in src/app/agent/prompts/system.md: "Default to type1
            # unless evidence … points to type2."
            rd["scd"] = "type1"
        renderable_dims.append(rd)

    return tpl.render(
        generator=_generator_name(),
        proposal_id=proposal.get("id", "(unsaved)"),
        version=proposal.get("version", 1),
        catalog=catalog,
        schema=schema,
        silver_schema=silver_schema,
        dims=renderable_dims,
        facts=proposal.get("facts", []),
    )
